### ISSUE TITLE
Help with PARSE and COLLAPSE installation

### ISSUE THREAD

**Issue by gioodm** [awfderry/PARSE#1]
Good morning,

I am trying to install PARSE on a HPC. I am using the cpu only instructions, as I had run into additional issues when trying to use cuda - ideally it would be nice to install it and being able to use a gpu, but it is not strictly necessary for now. 

After following the instructions found on the README.md, the program did not work as, while you don't specify it in the installation guide, I think PARSE also depends on COLLAPSE. However, the two of them depend on two different versions of PyTorch (2.0.0 for PARSE and 1.13.1 for COLLAPSE), which could result in packages conflicts. I continued the installation using the latest version of PyTorch =2.0.0

After this, the installation seemed to have worked correctly (I had to modify some instructions to install correctly gvp-pytorch as well as "pip install torch_scatter torch_sparse torch_cluster -f https://data.pyg.org/whl/torch-2.0.0+cu117.html". 
However, whenever I try to run a simple prediction on one .pdb structure, as following:

`(base) bash-4.4$ cd PARSE_dir/PARSE/`
`(base) bash-4.4$ conda activate parse_env`
`(parse_env) bash-4.4$ python3 predict.py --pdb /rds/general/user/gd1122/projects/rlalab/live/AF-Q6C8F7-F1-model_v4.pdb`

this generates the error:

`(parse_env) bash-4.4$ python3 predict.py --pdb /rds/general/user/gd1122/projects/rlalab/live/AF-Q6C8F7-F1-model_v4.pdb
/rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/torch_geometric/typing.py:54: UserWarning: An issue occurred while importing 'pyg-lib'. Disabling its usage. Stacktrace: /lib64/libm.so.6: version GLIBC_2.29' not found (required by /rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/libpyg.so)
  warnings.warn(f"An issue occurred while importing 'pyg-lib'. "
/rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/torch_geometric/typing.py:99: UserWarning: An issue occurred while importing 'torch-spline-conv'. Disabling its usage. Stacktrace: /rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/torch_spline_conv/_version_cpu.so: undefined symbol: _ZN3c1017RegisterOperatorsD1Ev
  warnings.warn(
/rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/torch_geometric/typing.py:110: UserWarning: An issue occurred while importing 'torch-sparse'. Disabling its usage. Stacktrace: /lib64/libm.so.6: version GLIBC_2.29' not found (required by /rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/libpyg.so)
  warnings.warn(f"An issue occurred while importing 'torch-sparse'. "
Traceback (most recent call last):
  File "/rds/general/project/rlalab/live/PARSE_dir/PARSE/predict.py", line 29, in <module>
    model = initialize_model(device=device)
  File "/rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/collapse/data.py", line 186, in initialize_model
    dummy_graph = torch.load(os.path.join(DATA_DIR, 'dummy_graph.pt'))
  File "/rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '/rds/general/user/gd1122/home/anaconda3/envs/parse_env/lib/python3.10/site-packages/collapse/../data/dummy_graph.pt'`

I am not sure about the FileNotFoundError, but I believe it might be linked to some of the previous code not running correctly. Instead apparently the previous warnings indicate issues with importing certain libraries (pyg-lib, torch-spline-conv, and torch-sparse). These warnings are related to missing or incompatible shared libraries (libm.so.6 with GLIBC_2.29 and undefined symbols). 

When printing the version of GLIBC:

`(parse_env) bash-4.4$ ldd --version
ldd (GNU libc) 2.28
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.`

Therefore I believe the issue is a mismatch between the gnu versions. 

I don't have a lot of previous experience with this, and I believe it is not feasible to update GLIBC on our HPC (as this might affect other users). Since our platform uses Easy-build, I have also been in contact with our support HPC team to try to install each package separately using easy-build, but we encountered additional issues because of poorly documented and versioned dependencies.

Is there an alternative way to install PARSE? For instance, would you be able to provide a Singularity / Docker container? Alternatively, can you suggest the version of each of the packages used to run PARSE on your system / can you indicate which versions are compatible with the GLIBC version on my HPC?
Am I making any obvious mistakes during the installation process that you can point out?

Any help would be greatly appreciated. Please let me know if you need further details, information, or files.
Thank you in advance for your assistance.

Best,
Giorgia

**Comment by RayHackett** [comment]
I am having similar issues. My current attempts at installing PARSE failed on some of the imports requried with lead me to:
- clone your COLLAPSE library and pip install it
- clone the gvp-pytorch library and pip install it (modifying the `setup.py`  from `skelarn` to `scikit-learn`)
- finding a numpy 2.x compatibility issue and downgrading to numpy 1.26
- running into `fileNotFoundError: [Errno 2] No such file or directory: './data/csa_site_db_nn.pkl'`
- running into `fileNotFoundError: [Errno 2] No such file or directory: './data/csa_function_sets_nn.pkl`
- running into `fileNotFoundError: [Errno 2] No such file or directory: './data/function_score_dists.pkl'`
- and downloading that all from zenodo
- running into
```
Traceback (most recent call last):
  File "[path to my clone of the parse repo]/PARSE/predict.py", line 28, in <module>
    background_dists = utils.deserialize(args.background)
  File "[path to my clone of the parse repo]PARSE/utils.py", line 10, in deserialize
    return pickle.load(fh)
_pickle.UnpicklingError: pickle data was truncated
```
and then giving up - sorry.

Could you give me some tips?

**Comment by RayHackett** [comment]
I am having similar issues. My current attempts at installing PARSE failed on some of the imports requred with lead me to:
- cloning your `COLLAPSE` repo and pip installing it
- cloning the `gpv-pytorch` library and pip installing it (modifying `setup.py` from `sklearn` to `scikit-learn`)
- finding a numpy 2.x compatibility issue and downgrading to numpy 1.26
- running into 3 `fileNotFoundError` for `csa_site-db_nn.pkl`, `csa_function_sets_nn.pkl` and `function_score_dists.pkl`
- downloading them all from zenodo
- running into another `fileNotFoundError` for `site-packages/collapse/../data/dummy_graph.pt`

and then giving up - sorry.
Could you give me some tips?

**Comment by gokceuludogan** [comment]
> * running into another `fileNotFoundError` for `site-packages/collapse/../data/dummy_graph.pt`

This happens because the data/ directory isn’t included in the collapse package when it's installed. As a workaround, cloning the collapse repo and placing data/ alongside the package source makes it work locally.
